name = "skymap-web"
main = "web-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "skymap-web"
route = "directory.ozoneskymap.fema.monster/*"

[[env.production.vars]]
DATABASE_URL = "postgresql://dev:devpass@localhost:5435/skymap"
WEB_API_URL = "http://localhost:3008"